apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-v2
  namespace: istio-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v2
  template:
    metadata:
      labels:
        app: demo-app
        version: v2
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0
          args:
            - "-text=Hello from application v2"
          ports:
            - containerPort: 5678
