apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db-credentials
  namespace: default
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: db-credentials

  data:
    - secretKey: username
      remoteRef:
        key: eso-lab/db-credentials
        property: username

    - secretKey: password
      remoteRef:
        key: eso-lab/db-credentials
        property: password